#!/usr/bin/env python3
"""Generate src/gamedata.cpp from research/{items,entities,locations}.json (static data extracted from the
server's enshrouded_server.kfc, build noted in each file's "source"). Re-run after a game update re-extracts them."""
import json, os, uuid

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.normpath(os.path.join(HERE, '..', '..', '..', 'research'))
OUT = os.path.normpath(os.path.join(HERE, '..', 'src', 'gamedata.cpp'))


def c(s):
    return json.dumps(s if s is not None else '', ensure_ascii=True)


def guid_bytes(g):
    return ','.join('0x%02x' % b for b in uuid.UUID(g).bytes)


items = json.load(open(os.path.join(RES, 'items.json')))
ents = json.load(open(os.path.join(RES, 'entities.json')))
locs = json.load(open(os.path.join(RES, 'locations.json')))

o = ['// GENERATED by tools/gen_gamedata.py - do not edit.', '#include "gamedata.h"', '',
     '// source: ' + items['source'], 'const ItemDef kItems[] = {']
for i in items['items']:
    pide = 1 if 'HasPIDE' in (i.get('flags') or []) else 0
    o.append('  {%du,%d,%d,%s,%s,%s,%s},' % (i['itemId'], i['maxStackSize'], pide, c(i['code']), c(i['name']),
                                         c(i['category']), c(i['rarity'])))
o.append('};')
o.append('const size_t kItemCount = sizeof(kItems) / sizeof(kItems[0]);')
o.append('')
o.append('// source: ' + ents['source'])
o.append('const EntityDef kEntities[] = {')
for e in ents['entities']:
    o.append('  {{%s},%s,%s,%s,%s},' % (guid_bytes(e['templateGuid']), c(e['code']), c(e['type']), c(e['family']),
                                    c(e['faction'])))
o.append('};')
o.append('const size_t kEntityCount = sizeof(kEntities) / sizeof(kEntities[0]);')
o.append('')
o.append('// source: ' + locs['source'])
o.append('const LocationDef kLocations[] = {')
for l in locs['locations']:
    o.append('  {%s,%s,%s,%r,%r,%r},' % (c(l['code']), c(l['kind']), c(l.get('spawnType')), float(l['x']), float(l['y']),
                                       float(l['z'])))
o.append('};')
o.append('const size_t kLocationCount = sizeof(kLocations) / sizeof(kLocations[0]);')
open(OUT, 'w').write('\n'.join(o) + '\n')
print('wrote', OUT, len(items['items']), len(ents['entities']), len(locs['locations']))
