#!/usr/bin/env python3
"""Generate src/itemlabels.cpp: English item display names and weapon category names.

The dedicated server ships no localisation, so the names come from the game client. Export them
offline with the Enshrouded Mod Loader CLI (github.com/Brabb3l/kfc-parser, `emm run -e`) and the
export mod in tools/eml-export/, against a client directory holding enshrouded.exe, enshrouded.kfc,
enshrouded.kfc_resources and the .dat that holds the En_Us loca data. That writes
items-en.tsv (itemId, debugName, En_Us name, category, weaponCategoryId).

    gen_item_labels.py <export-dir> [build note]
"""
import os
import re
import sys
import json

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, '..', 'src', 'itemlabels.cpp'))

# The client's WeaponCategory resources do not resolve offline, so each WeaponCategoryId (the FNV-1a
# hash of the category guid, as ItemInfo.weaponCategoryReference names it) is named from the item
# codes that carry it: the first keyword, in this order, that one of its items' codes contains.
KEYWORDS = [('unarmed', 'Unarmed'), ('greatsword', 'Greatsword'), ('greataxe', 'Greataxe'), ('dagger', 'Daggers'),
            ('sword', 'Sword'), ('bow', 'Bow'), ('staff', 'Staff'), ('wand', 'Wand'), ('mace', 'Mace'),
            ('hammer', 'Hammer'), ('axe', 'Axe'), ('grenade', 'Throwable'), ('torch', 'Tool')]


def c(s):
    return json.dumps(s, ensure_ascii=True)


def main():
    exp = sys.argv[1]
    note = sys.argv[2] if len(sys.argv) > 2 else ''
    items, codes = {}, {}
    for line in open(os.path.join(exp, 'items-en.tsv'), encoding='utf-8'):
        f = line.rstrip('\n').split('\t')
        if len(f) < 5 or not f[0]:
            continue
        # The client's markup (<npc>, <lorename>, <craftingstation>, ...) is styling, not text.
        name = ' '.join(re.sub(r'</?[A-Za-z]+>', '', f[2]).split())
        if name:
            items[int(f[0])] = name
        if f[4]:
            codes.setdefault(int(f[4]), []).append(f[1].lower())
    cats = {}
    for cid, cs in codes.items():
        for kw, name in KEYWORDS:
            if any(kw in x for x in cs):
                cats[cid] = name
                break
    o = ['// GENERATED by tools/gen_item_labels.py - do not edit.', '#include "weapon.h"', '',
         '// source: game client En_Us localisation' + (', ' + note if note else ''),
         'const ItemLabel kItemLabels[] = {']
    o += ['  {%du,%s},' % (k, c(items[k])) for k in sorted(items)]
    o += ['};', 'const size_t kItemLabelCount = sizeof(kItemLabels) / sizeof(kItemLabels[0]);', '',
          'const WeaponCategoryLabel kWeaponCategoryLabels[] = {']
    o += ['  {%du,%s},' % (k, c(cats[k])) for k in sorted(cats)]
    o += ['};', 'const size_t kWeaponCategoryLabelCount = sizeof(kWeaponCategoryLabels) / sizeof(kWeaponCategoryLabels[0]);', '']
    open(OUT, 'w').write('\n'.join(o))
    print('wrote %s: %d items, %d weapon categories' % (OUT, len(items), len(cats)))


main()
