#!/usr/bin/env python3
"""Generate src/entitylabels.cpp: English display names of entity templates, from the game client.

The dedicated server ships no localisation, and the client names only the creatures it shows a name
for: bosses and mini-bosses through their health bar (BossHealthBar.displayName) and NPCs through
their LocaTagComponent. A regular creature such as Enemy_Wildbeast_Rat_hook has no display name in
the client at all (the En_Us table holds no "Rat"), so it is left to the code-derived name in
names.cpp.

Export the names offline with the Enshrouded Mod Loader CLI (`emm run -e`) and the export mod in
tools/eml-export/ (see gen_item_labels.py); that writes templates-en.tsv (template guid, code,
En_Us name, which component named it).

A template the client does not name inherits the name of a named sibling: the same code once the
spawn and bookkeeping suffixes are dropped (Enemy_Fogger_Heavy_SummonStone and
Enemy_Fogger_Heavy_hookPtE are both Enemy_Fogger_Heavy, whose _BossHealthBar variant the client
calls "Fell Thunderbrute"). A key that two different names claim is left alone.

A fish is named by the client through its catch: Fish_T1_common_01 and
Animal_wildlife_Fish_T1_common_01_tame are the fish the raw-fish item _Food_raw_T1_fish_common_01
("Shimmerfin") is, so they take that item's En_Us name (items-en.tsv from the same export).

    gen_entity_labels.py <export-dir> <entities.json> [build note]

entities.json is the server template table gen_gamedata.py bakes into gamedata.cpp.
"""
import json
import os
import re
import sys
import uuid

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, '..', 'src', 'entitylabels.cpp'))

# Suffix tokens that mark how a template is spawned or tracked, not what creature it is.
SIBLING_NOISE = {'hook', 'hookpte', 'ag2', 'bosshealthbar', 'bosshealtbar', 'healthbar', 'summonstone', 'cave', '8k'}


def c(s):
    return json.dumps(s, ensure_ascii=True)


def clean(name):
    """The client's markup (<npc>, <lorename>, ...) is styling, not text."""
    return ' '.join(re.sub(r'</?[A-Za-z]+>', '', name).split())


def sibling_key(code):
    out = []
    for tok in code.lower().split('_'):
        if not tok or tok in SIBLING_NOISE or re.fullmatch(r'version\d+|\d+', tok):
            continue
        out.append(re.sub(r'\d+$', '', tok))
    return ' '.join(out)


FISH_ITEM = re.compile(r'_?Food_raw(?:_bad)?_(t\d)_fish_([a-z]+)_(\d+)$', re.I)
FISH_ENTITY = re.compile(r'(?:animal_wildlife_)?fish_(t\d)_([a-z]+)_(\d+)(?:_tame)?$', re.I)


def fish_names(exp):
    out = {}
    for line in open(os.path.join(exp, 'items-en.tsv'), encoding='utf-8'):
        f = line.rstrip('\n').split('\t')
        m = FISH_ITEM.match(f[1]) if len(f) > 2 else None
        if m and clean(f[2]):
            out[tuple(x.lower() for x in m.groups())] = clean(f[2])
    return out


def main():
    exp = sys.argv[1]
    note = sys.argv[3] if len(sys.argv) > 3 else ''
    client = {}
    for line in open(os.path.join(exp, 'templates-en.tsv'), encoding='utf-8'):
        f = line.rstrip('\n').split('\t')
        if len(f) >= 3 and f[0]:
            client[f[0].lower()] = (f[1], clean(f[2]))
    ents = json.load(open(sys.argv[2]))['entities']

    named, keys = {}, {}
    for e in ents:
        code, name = client.get(e['templateGuid'].lower(), ('', ''))
        if name:
            named[e['templateGuid']] = (name, 'client')
            keys.setdefault(sibling_key(e['code']), set()).add(name)
    for e in ents:
        if e['templateGuid'] in named:
            continue
        claim = keys.get(sibling_key(e['code']))
        if claim and len(claim) == 1:
            named[e['templateGuid']] = (next(iter(claim)), 'sibling')

    fish = fish_names(exp)
    for e in ents:
        m = FISH_ENTITY.match(e['code'])
        if e['templateGuid'] not in named and m and tuple(x.lower() for x in m.groups()) in fish:
            named[e['templateGuid']] = (fish[tuple(x.lower() for x in m.groups())], 'fishItem')

    rows = sorted(named.items(), key=lambda kv: uuid.UUID(kv[0]).bytes)
    o = ['// GENERATED by tools/gen_entity_labels.py - do not edit.', '#include "entity.h"', '',
         '// source: game client En_Us localisation' + (', ' + note if note else ''),
         'const EntityLabel kEntityLabels[] = {']
    for g, (name, src) in rows:
        o.append('  {{%s},%s,%s},' % (','.join('0x%02x' % b for b in uuid.UUID(g).bytes), c(name), c(src)))
    o += ['};', 'const size_t kEntityLabelCount = sizeof(kEntityLabels) / sizeof(kEntityLabels[0]);', '']
    open(OUT, 'w').write('\n'.join(o))
    by = {}
    for _, (_, src) in rows:
        by[src] = by.get(src, 0) + 1
    print('wrote %s: %d of %d templates named (%d by the client, %d from a named sibling, %d fish by their catch)' %
          (OUT, len(rows), len(ents), by.get('client', 0), by.get('sibling', 0), by.get('fishItem', 0)))


main()
